plugins {
    id 'fabric-loom' version '1.0-SNAPSHOT'
}

version = "${minecraft_version}-${mod_version}"
archivesBaseName = "${mod_id}-fabric"

dependencies {
    minecraft "com.mojang:minecraft:${minecraft_version}"
    mappings loom.officialMojangMappings()
    modImplementation "net.fabricmc:fabric-loader:${fabric_loader_version}"
    modImplementation "net.fabricmc.fabric-api:fabric-api:${fabric_version}"
    implementation project(":common")
}

loom {
    mixin.defaultRefmapName = "healthcommand.refmap.json"
    runs {
        client {
            client()
            setConfigName("Fabric Client")
            ideConfigGenerated(true)
            runDir("run")
        }
        server {
            server()
            setConfigName("Fabric Server")
            ideConfigGenerated(true)
            runDir("run")
        }
    }
}

processResources {
    from project(":common").sourceSets.main.resources
}

tasks.withType(JavaCompile) {
    source(project(":common").sourceSets.main.allSource)
}
