plugins {
    id 'fabric-loom' version '0.7-SNAPSHOT'
}

sourceCompatibility = JavaVersion.VERSION_1_8
targetCompatibility = JavaVersion.VERSION_1_8

archivesBaseName = "healthcommand"
version = "fabric-${minecraft_version}-${mod_version}"

repositories {
    maven {
        url "https://maven.terraformersmc.com/releases"
    }
}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    mappings "net.fabricmc:yarn:${project.yarn_mappings}:v2"
    modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"
    modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"
    modImplementation "com.terraformersmc:modmenu:${modmenu_version}"
}


tasks.withType(JavaCompile).configureEach {
    it.options.encoding = "UTF-8"
    def targetVersion = 8
    if (JavaVersion.current().isJava9Compatible()) {
        it.options.release = targetVersion
    }
}

jar {
    from rootProject.file('LICENSE')
    manifest {
        attributes([
            'Specification-Title'     : mod_name,
            'Specification-Vendor'    : mod_author,
            'Specification-Version'   : project.jar.archiveVersion,
            'Implementation-Title'    : project.name,
            'Implementation-Version'  : project.jar.archiveVersion,
            'Implementation-Vendor'   : mod_author,
            'Implementation-Timestamp': new Date().format("yyyy-MM-dd'T'HH:mm:ssZ"),
            'Timestamp'               : System.currentTimeMillis(),
            'Built-On-Java'           : "${System.getProperty('java.vm.version')} (${System.getProperty('java.vm.vendor')})",
            'Build-On-Minecraft'      : minecraft_version
        ])
    }
}

processResources {
    def expandProps = [
        "version"                   : "${minecraft_version}-${mod_version}",
        "version_range"             : version_range,
        "minecraft_version"         : minecraft_version,
        "java_version"              : java_version,
        "fabric_loader_min"         : fabric_loader_min,
        "fabric_range_min_inclusive": fabric_range_min_inclusive,
        "fabric_range_max_exclusive": fabric_range_max_exclusive
    ]

    filesMatching(['fabric.mod.json']) {
        expand expandProps
    }
    inputs.properties(expandProps)
}
