# Project
group=com.tristankechlo.healthcommand

# Common
java_version=21
minecraft_version=1.21.6
version_range=[1.21.6, 1.21.9)
auto_service_version=1.1.1

# Forge
forge_version=56.0.9
forge_loader_range=[56,)

# Fabric
fabric_version=0.128.2+1.21.6
fabric_loader_version=0.17.2
fabric_loader_min=0.16
fabric_range_min_inclusive=1.21.6
fabric_range_max_exclusive=1.21.9

# Neoforge
# https://projects.neoforged.net/neoforged/neoform
neo_form_version=1.21.6-20250617.151856
# https://projects.neoforged.net/neoforged/neoforge
neoforge_version=21.6.20-beta
neoforge_loader_range=[4,)
neoforge_range=[21.6,)

# https://parchmentmc.org/docs/getting-started#choose-a-version
parchment_minecraft=1.21.6
parchment_version=2025.06.29

# Mod options
mod_name=HealthCommand
mod_author=Buecher_wurm
mod_version=1.4.2
mod_id=healthcommand

# Other options
modmenu_version=15.0.0

# Gradle
org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=false

