# Project
group=com.tristankechlo.healthcommand

# Common
java_version=21
minecraft_version=1.21.4
version_range=[1.21.3, 1.22)
auto_service_version=1.1.1

# Forge
forge_version=54.0.6
forge_loader_range=[53,)

# Fabric
fabric_version=0.112.0+1.21.4
fabric_loader_version=0.16.9
fabric_loader_min=0.16
fabric_range_min_inclusive=1.21.3
fabric_range_max_exclusive=1.22

# Neoforge
neo_form_version=1.21.4-20241203.161809
neoforge_version=21.4.23-beta
neoforge_loader_range=[4,)
neoforge_range=[21.3,)

parchment_minecraft=1.21.4
parchment_version=2024.12.07

# Mod options
mod_name=HealthCommand
mod_author=Buecher_wurm
mod_version=1.4.2
mod_id=healthcommand

# Other options
modmenu_version=13.0.0-beta.1

# Gradle
org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=false

