# Project
group=com.tristankechlo.healthcommand

# Common
java_version=17
minecraft_version=1.20.1
version_range=[1.20.1,1.20.2)

# Forge
forge_version=47.3.10
forge_loader_range=[47,)

# Fabric
fabric_version=0.92.1+1.20.1
fabric_loader_version=0.15.10
fabric_loader_min=0.15
fabric_range_min_inclusive=1.20.1
fabric_range_max_exclusive=1.20.2

# Mod options
mod_name=HealthCommand
mod_author=Buecher_wurm
mod_version=1.4.1
mod_id=healthcommand

# Other options
modmenu_version=7.1.0

# Gradle
org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=false

